module

import vanKampen.Theorem_70_1
public import vanKampen.Presentation
import all vanKampen.Presentation
import Mathlib.GroupTheory.QuotientGroup.Defs

public section

universe u

open CategoryTheory

/-- Helper for Theorem 70.2: a defect `(f x)⁻¹ * g x` belongs to a normal subgroup
exactly when `f` and `g` agree at `x` after passing to the quotient. -/
private lemma inv_mul_mem_iff_quotient_comp_eq {G H : Type*} [Group G] [Group H]
    (N : Subgroup H) [N.Normal] (f g : G →* H) (x : G) :
    (f x)⁻¹ * g x ∈ N ↔
      ((QuotientGroup.mk' N).comp f) x = ((QuotientGroup.mk' N).comp g) x := by
  -- Convert subgroup membership to a quotient equation and normalize both composites.
  rw [← QuotientGroup.eq_one_iff]
  simp only [QuotientGroup.mk_mul, QuotientGroup.mk_inv, MonoidHom.comp_apply,
    inv_mul_eq_one, QuotientGroup.mk'_apply]

/-- Helper for Theorem 70.2: the kernel of the canonical map from a free product to a
group pushout is normally generated by the defects coming from the common group. -/
private lemma coprodLift_ker_eq_normalClosure_invMul_range_of_isPushout
    {A B D P : Type u} [Group A] [Group B] [Group D] [Group P]
    (left : D →* A) (right : D →* B) (toPLeft : A →* P) (toPRight : B →* P)
    (pushout : CategoryTheory.IsPushout (GrpCat.ofHom left) (GrpCat.ofHom right)
      (GrpCat.ofHom toPLeft) (GrpCat.ofHom toPRight)) :
    (Monoid.Coprod.lift toPLeft toPRight).ker = Subgroup.normalClosure
      (Set.range fun x ↦
        ((Monoid.Coprod.inl.comp left) x)⁻¹ * (Monoid.Coprod.inr.comp right) x) := by
  classical
  let N : Subgroup (Monoid.Coprod A B) := Subgroup.normalClosure
    (Set.range fun x ↦
      ((Monoid.Coprod.inl.comp left) x)⁻¹ * (Monoid.Coprod.inr.comp right) x)
  let quotientLeft := (QuotientGroup.mk' N).comp
    (Monoid.Coprod.inl : A →* Monoid.Coprod A B)
  let quotientRight := (QuotientGroup.mk' N).comp
    (Monoid.Coprod.inr : B →* Monoid.Coprod A B)
  -- Pushout commutativity identifies the two maps from the common group into `P`.
  have hmaps : toPLeft.comp left = toPRight.comp right := by
    have hmapsCategory := congrArg GrpCat.Hom.hom pushout.w
    simpa only [GrpCat.hom_comp, GrpCat.hom_ofHom] using hmapsCategory
  -- The defining defects make the two coproduct maps compatible after quotienting by `N`.
  have hquotient : quotientLeft.comp left = quotientRight.comp right := by
    rw [MonoidHom.comp_assoc, MonoidHom.comp_assoc]
    apply MonoidHom.ext
    intro x
    exact (inv_mul_mem_iff_quotient_comp_eq N
      (Monoid.Coprod.inl.comp left) (Monoid.Coprod.inr.comp right) x).mp
      (Subgroup.subset_normalClosure ⟨x, rfl⟩)
  have hquotientCategory :
      GrpCat.ofHom left ≫ GrpCat.ofHom quotientLeft =
        GrpCat.ofHom right ≫ GrpCat.ofHom quotientRight := by
    rw [← GrpCat.ofHom_comp, ← GrpCat.ofHom_comp]
    exact congrArg GrpCat.ofHom hquotient
  let inverse : P →* Monoid.Coprod A B ⧸ N :=
    (pushout.desc (GrpCat.ofHom quotientLeft) (GrpCat.ofHom quotientRight)
      hquotientCategory).hom
  -- The pushout computation rules identify the restrictions of the descended inverse.
  have hinverseLeft : inverse.comp toPLeft = quotientLeft := by
    apply GrpCat.ofHom_injective
    simpa only [GrpCat.ofHom_comp, GrpCat.ofHom_hom, inverse] using
      pushout.inl_desc (GrpCat.ofHom quotientLeft) (GrpCat.ofHom quotientRight)
        hquotientCategory
  have hinverseRight : inverse.comp toPRight = quotientRight := by
    apply GrpCat.ofHom_injective
    simpa only [GrpCat.ofHom_comp, GrpCat.ofHom_hom, inverse] using
      pushout.inr_desc (GrpCat.ofHom quotientLeft) (GrpCat.ofHom quotientRight)
        hquotientCategory
  -- Commutativity of the pushout kills every defining defect.
  have hnormalClosure_le : N ≤ (Monoid.Coprod.lift toPLeft toPRight).ker := by
    apply Subgroup.normalClosure_le_normal
    rintro _ ⟨x, rfl⟩
    apply MonoidHom.mem_ker.mpr
    have hmapsValue := DFunLike.congr_fun hmaps x
    simpa only [map_mul, map_inv, MonoidHom.comp_apply,
      Monoid.Coprod.lift_apply_inl, Monoid.Coprod.lift_apply_inr,
      inv_mul_eq_one] using hmapsValue
  -- On both free-product factors, the descended inverse agrees with the quotient map.
  have hinverseComp :
      inverse.comp (Monoid.Coprod.lift toPLeft toPRight) = QuotientGroup.mk' N := by
    apply Monoid.Coprod.hom_ext
    · rw [MonoidHom.comp_assoc, Monoid.Coprod.lift_comp_inl, hinverseLeft]
    · rw [MonoidHom.comp_assoc, Monoid.Coprod.lift_comp_inr, hinverseRight]
  -- Applying that inverse to a kernel element places the element in `N`.
  have hker_le : (Monoid.Coprod.lift toPLeft toPRight).ker ≤ N := by
    intro x hx
    apply (QuotientGroup.eq_one_iff x).mp
    have hcoprodValue : Monoid.Coprod.lift toPLeft toPRight x = 1 :=
      MonoidHom.mem_ker.mp hx
    have hinverseValue := DFunLike.congr_fun hinverseComp x
    calc
      (x : Monoid.Coprod A B ⧸ N) = (QuotientGroup.mk' N) x :=
        (QuotientGroup.mk'_apply N x).symm
      _ = inverse (Monoid.Coprod.lift toPLeft toPRight x) := hinverseValue.symm
      _ = inverse 1 := congrArg inverse hcoprodValue
      _ = 1 := map_one inverse
  exact le_antisymm hker_le hnormalClosure_le

/-- Helper for Theorem 70.2: `vanKampenRelation` is the inverse-product defect of the
two maps from the intersection fundamental group into the free product. -/
private lemma vanKampenRelation_eq_invMul {X : Type u} [TopologicalSpace X]
    (U V : Set X) (x₀ : X) (hx₀ : x₀ ∈ U ∩ V) :
    FundamentalGroup.vanKampenRelation U V x₀ hx₀ = fun g ↦
      ((Monoid.Coprod.inl.comp
        (FundamentalGroup.mapOfSubset Set.inter_subset_left ⟨x₀, hx₀⟩)) g)⁻¹ *
      (Monoid.Coprod.inr.comp
        (FundamentalGroup.mapOfSubset Set.inter_subset_right ⟨x₀, hx₀⟩)) g := by
  -- Compare the two functions on an intersection loop and expose the presentation formula.
  funext g
  simp only [FundamentalGroup.vanKampenRelation.eq_def, MonoidHom.comp_apply]

/-- Theorem 70.2 (1): The canonical homomorphism from the free product of the fundamental
groups of `U` and `V` to the fundamental group of `X` is surjective. -/
theorem vanKampenMap_surjective {X : Type u} [TopologicalSpace X]
    (U V : Set X) (x₀ : X) (hx₀ : x₀ ∈ U ∩ V)
    (hU : IsOpen U) (hV : IsOpen V) (hcover : U ∪ V = Set.univ)
    [PathConnectedSpace U] [PathConnectedSpace V]
    [PathConnectedSpace (U ∩ V : Set X)] :
    Function.Surjective (FundamentalGroup.vanKampenMap U V x₀ hx₀) := by
  -- The range of the free-product lift is the join of the two inclusion-map ranges.
  apply MonoidHom.range_eq_top.mp
  rw [FundamentalGroup.vanKampenMap.eq_def, Monoid.Coprod.range_lift]
  -- The earlier generation theorem says that this join is the whole fundamental group.
  exact fundamentalGroupMap_range_sup_range_eq_top U V x₀ hx₀ hU hV hcover

/-- Companion to Theorem 70.2: The kernel of the canonical free-product homomorphism is the least
normal subgroup containing the relations induced by loops in `U ∩ V`. -/
theorem vanKampenMap_ker {X : Type u} [TopologicalSpace X]
    (U V : Set X) (x₀ : X) (hx₀ : x₀ ∈ U ∩ V)
    (hU : IsOpen U) (hV : IsOpen V) (hcover : U ∪ V = Set.univ)
    [PathConnectedSpace U] [PathConnectedSpace V]
    [PathConnectedSpace (U ∩ V : Set X)] :
    (FundamentalGroup.vanKampenMap U V x₀ hx₀).ker =
      FundamentalGroup.vanKampenNormalClosure U V x₀ hx₀ := by
  -- Apply the abstract pushout kernel formula to the three inclusion-induced maps.
  simpa only [FundamentalGroup.vanKampenMap.eq_def,
    FundamentalGroup.vanKampenNormalClosure.eq_def,
    FundamentalGroup.vanKampenRelations.eq_def,
    vanKampenRelation_eq_invMul, MonoidHom.comp_apply] using
    coprodLift_ker_eq_normalClosure_invMul_range_of_isPushout
      (FundamentalGroup.mapOfSubset Set.inter_subset_left ⟨x₀, hx₀⟩)
      (FundamentalGroup.mapOfSubset Set.inter_subset_right ⟨x₀, hx₀⟩)
      (FundamentalGroup.mapOfSubtype U ⟨x₀, hx₀.1⟩)
      (FundamentalGroup.mapOfSubtype V ⟨x₀, hx₀.2⟩)
      (FundamentalGroup.isPushoutOfOpenUnion_of_pathConnected
        U V x₀ hx₀ hU hV hcover)
